# Generated by Django 3.1.3 on 2023-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=10)),
                ('prod_name', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField(max_length=100)),
                ('tot_cost', models.FloatField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('photo', models.CharField(max_length=500)),
                ('d_date', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('userid', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=10)),
                ('prod_name', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField(max_length=100)),
                ('tot_cost', models.FloatField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('sid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=10)),
                ('cat_name', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('availability', models.IntegerField()),
                ('sid', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('qid', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
