# Generated by Django 3.1.3 on 2023-03-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='qid',
            new_name='question',
        ),
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='intrests',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='year',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
