# Generated by Django 3.1.3 on 2023-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230322_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='email',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='keywords',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='stz',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
