# Generated by Django 3.1.3 on 2023-03-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='d_date',
        ),
    ]
