# Generated by Django 3.1.3 on 2023-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
